#!/usr/bin/env python3
"""Plot NVDA close prices around news events from a CSV generated by data_fetching.py."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter


def plot_close_prices(csv_path: Path, output_path: Path | None = None) -> None:
    df = pd.read_csv(
        csv_path,
        parse_dates=["timestamp (UTC)", "timestamp (America/New_York)"],
    )
    if df.empty:
        raise SystemExit(f"No rows found in {csv_path}")

    timestamp_col = (
        "timestamp (America/New_York)"
        if "timestamp (America/New_York)" in df.columns
        else "timestamp (UTC)"
    )

    fig, ax = plt.subplots(figsize=(10, 5))
    if "event_id" in df.columns:
        for event_id, group in df.groupby("event_id"):
            ax.plot(group[timestamp_col], group["close"], label=f"Event {event_id}")
    else:
        ax.plot(df[timestamp_col], df["close"], label="NVDA Close Price")

    ax.set_title("NVDA Close Prices (Regular Trading Hours)")
    ax.set_xlabel("Time (America/New_York)")
    ax.set_ylabel("Close Price (USD)")
    ax.legend()
    ax.grid(True, alpha=0.3)

    date_formatter = DateFormatter("%m-%d %H:%M")
    ax.xaxis.set_major_formatter(date_formatter)
    fig.autofmt_xdate()

    if output_path:
        fig.savefig(output_path, bbox_inches="tight")
        print(f"Saved plot to {output_path}")
    else:
        plt.show()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Plot close prices from NVDA news reaction CSV")
    parser.add_argument("csv", type=Path, help="Path to nvda_prices_around_news_YYYY-MM-DD.csv")
    parser.add_argument("--output", type=Path, help="Optional path to save the plot image")
    args = parser.parse_args()

    plot_close_prices(args.csv, args.output)
