#!/usr/bin/env python3
"""Plot NVDA close prices around news events from a CSV generated by data_fetching.py."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt


def plot_close_prices(csv_path: Path, output_path: Path | None = None) -> None:
    df = pd.read_csv(csv_path, parse_dates=["timestamp"])
    if df.empty:
        raise SystemExit(f"No rows found in {csv_path}")

    fig, ax = plt.subplots(figsize=(10, 5))
    for event_id, group in df.groupby("event_id"):
        ax.plot(group["timestamp"], group["close"], label=f"Event {event_id}")

    ax.set_title("NVDA Close Prices Around News Events")
    ax.set_xlabel("Timestamp (UTC)")
    ax.set_ylabel("Close Price (USD)")
    ax.legend()
    ax.grid(True, alpha=0.3)

    if output_path:
        fig.savefig(output_path, bbox_inches="tight")
        print(f"Saved plot to {output_path}")
    else:
        plt.show()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Plot close prices from NVDA news reaction CSV")
    parser.add_argument("csv", type=Path, help="Path to nvda_prices_around_news_YYYY-MM-DD.csv")
    parser.add_argument("--output", type=Path, help="Optional path to save the plot image")
    args = parser.parse_args()

    plot_close_prices(args.csv, args.output)
