import subprocess
import os
import glob
import shutil
import yaml

CONFIG_FILE = "nvidia-config.yaml"
FETCH_SCRIPT = "fetch_prices.py"
TARGET_DATE_FILE = "targetSimDate.txt"


def read_target_date():
    with open(TARGET_DATE_FILE, "r") as f:
        return f.read().strip()  # format: YYYY-MM-DD


def get_config_date(path):
    with open(path, "r") as f:
        cfg = yaml.safe_load(f)
    return cfg["defaults"]["date"]


def set_config_date(path, new_date):
    with open(path, "r") as f:
        cfg = yaml.safe_load(f)
    cfg["defaults"]["date"] = new_date
    with open(path, "w") as f:
        yaml.safe_dump(cfg, f)


def run_fetch_script():
    subprocess.run(["python", FETCH_SCRIPT, "--config", CONFIG_FILE], check=True)


def find_generated_csv(date_str):
    folder = f"NVDA_{date_str}"
    if not os.path.isdir(folder):
        raise FileNotFoundError(f"Folder not found: {folder}")

    pattern = os.path.join(folder, f"nvda_prices_around_news_{date_str}*.csv")
    files = glob.glob(pattern)
    if not files:
        raise FileNotFoundError("CSV not found with expected naming pattern.")

    return files[0]


def copy_csv_to_working_directory(src_csv):
    filename = os.path.basename(src_csv)
    dest = os.path.join(os.getcwd(), filename)
    shutil.copy(src_csv, dest)
    return dest


def main():
    original_date = get_config_date(CONFIG_FILE)
    target_date = read_target_date()

    print(f"\n📌 Fetching NVDA data for: {target_date}\n")

    try:
        # Update date in YAML
        set_config_date(CONFIG_FILE, target_date)

        # Run fetch script
        run_fetch_script()

        # Locate CSV generated by fetch script
        # Step: Locate CSV generated by fetch script
        csv_path = find_generated_csv(target_date)

        # Copy the CSV to working directory
        new_path = copy_csv_to_working_directory(csv_path)
        print(f"📄 CSV copied to working dir:\n   → {new_path}")

        # Rename/move to standard filename used by the simulation script
        final_csv_path = os.path.join(os.getcwd(), "NVDA_prices.csv")
        os.replace(new_path, final_csv_path)
        print(f"📌 CSV ready for simulation:\n   → {final_csv_path}")

    finally:
        # Restore original date ALWAYS
        set_config_date(CONFIG_FILE, original_date)
        print(f"\n🔄 YAML date restored to original: {original_date}")

    print("\n✅ All done!")


if __name__ == "__main__":
    main()
